### ISSUE TITLE
Item duplication: Steel pickaxe

### ISSUE THREAD

**Issue by sbrl** [t-affeldt/handholds_redo#1]
Ref https://github.com/minetest-mods/anvil/issues/22, you're not returning the itemstack correctly here: https://github.com/t-affeldt/handholds_redo/blob/9496c8612a9f0bc3f234c1439df2bbe8dff8de2f/init.lua#L20-L25

**Comment by t-affeldt** [comment]
Thank you for letting me know! I was able to replicate the issue, fix it, and make sure that it now works as intended.

**Comment by MetaNomad** [comment]
> Thank you for letting me know! I was able to replicate the issue, fix it, and make sure that it now works as intended.

Updated it via ContentDB, and everything is working fine now, thx :-)
